import {useEffect,useMemo,useState} from 'react';
import type {Trade} from '../types';
const NO_TRADES:Trade[]=[];
import RatCare from './RatCare';
import Hud from './Hud';
import HabitatComparison from './HabitatComparison';
import Memorial from './Memorial';
import {getWorld,useStore} from '../store';
import {affinity} from '../sim/social';
import {colonyMetrics} from '../sim/colonyMetrics';
import {playActivity} from '../sim/playActivity';
import {colonyAlerts,alertResidents} from './colonyAlerts';
import {tr,locale,useLanguage} from '../i18n';
const labels:Record<string,[string,string]>={hunger:['Hunger','饥饿'],thirst:['Water scarcity','水资源不足'],cold:['Cold load','寒冷负荷'],hot:['Heat load','炎热负荷'],stress:['Stress','压力'],crowdPressure:['Local crowding','局部拥挤'],isolation:['Prolonged isolation','持续孤立'],dehydrated:['Low hydration','水合水平低'],exhausted:['Low energy','能量不足'],injured:['Injuries','受伤'],criticalStress:['Critical stress','严重压力'],capacity:['Population limit','种群数量上限'],localCapacity:['Overloaded shelter','庇护区过度拥挤'],conflicts:['Recent conflicts','近期冲突'],declining:['Population declining','种群数量下降'],extinct:['Colony extinct','种群灭绝']};
const tones:Record<string,[string,string]>={'critical local crowding':['Critical local crowding','局部严重拥挤'],'alarm / retreat':['Alert and seeking shelter','警戒并寻找庇护'],'huddling for warmth':['Huddling for warmth','聚集取暖'],'crowding tension':['Crowding tension','拥挤引发紧张'],'collective foraging':['Foraging together','共同觅食'],'stable social clusters':['Stable social groups','社群稳定'],'dispersed exploration':['Dispersed exploration','分散探索']};
const actionLabels:Record<string,[string,string]>={wheel:['Running in the wheel','跑轮运动'],digging:['Digging','挖掘'],ball:['Playing with a ball','玩球'],chewing:['Gnawing','啃咬'],foraging:['Foraging','觅食'],courtship:['Courtship','求偶'],mating:['Mating','交配'],fight:['Fighting','争斗'],groom:['Social grooming','社交梳理']};
export default function ColonyPanel(){
 const [tab,setTab]=useState('colony');
 const panel=useStore(s=>s.panel),panelRequest=useStore(s=>s.panelRequest);

 useLanguage(s=>s.language);const version=useStore(s=>s.version),focused=useStore(s=>s.focusedId),trades=useStore(s=>tab==='events'?s.trades:NO_TRADES);
 const world=getWorld(),m=useMemo(()=>colonyMetrics(world),[world,version]),rat=focused?world.rats[focused]:undefined,alerts=colonyAlerts(world,m),critical=alerts.filter(a=>a.critical).length;
 useEffect(()=>{setTab(panel==='rat'?'rat':'colony');},[panel,focused,panelRequest]);
 const bonds=rat?Object.values(world.rats).filter(r=>r.id!==rat.id&&r.deadAt===null).map(r=>({r,value:affinity(world,rat,r)})).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,5):[];
 const current=rat?actionLabels[rat.socialAction?.kind??playActivity.get(rat.id)?.kind??'']:undefined;
 return <div className="colony-readout" data-severity={critical?'critical':alerts.length?'warning':'good'}>
 <div className="panel-head"><strong>{tr('Observatory','观察站')}</strong><span className="dim">{tr('Day','第')} {Math.floor(world.simDay)}{tr('','天')}</span></div>
 <nav className="readout-tabs" aria-label={tr('Colony information','种群信息')}>{[['colony',tr('Colony','种群')],['rat',tr('Rat','个体')],['events',tr('Events','事件')],['memorial',tr('Memorial','纪念')]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {alerts.length>0&&<button className={`alert-banner ${critical?'critical':''}`} onClick={()=>setTab('colony')} aria-label={tr('View colony alerts','查看种群警报')}><span className="alert-signal" aria-hidden="true"/><b>{critical?tr('Critical','危急'):tr('Warning','警告')}</b> · {alerts.length} {tr('active alerts','项当前警报')}{critical>0&&<span> · {critical} {tr('critical','项危急')}</span>}</button>}
 <div className="readout-content">
 {world.permanentCore&&<p className="attention-note">{tr('Permanent core · 6 residents receive automatic care and cannot die. Other residents follow their normal life cycle.','永久核心 · 6只居民自动受到照护，不会死亡。其他居民遵循正常生命周期。')}</p>}
 {world.careProtection?.active&&<p className="attention-note">{tr('Temporary assisted care active · normal rules resume automatically.','临时照护已启用，到期后自动恢复正常规则。')}</p>}
 {tab==='colony'&&<>
 <div className={`colony-state ${alerts.length?'is-alert':''}`}><span>{tr('Collective condition','群体状态')}</span><strong>{!m.n?tr('Colony extinct','种群灭绝'):critical?tr('Urgent attention needed','需要紧急关注'):alerts.length?tr('Conditions deteriorating','状态恶化中'):tr(...(tones[m.socialTone]??['Settling','适应中']))}</strong><p>{m.n} / {m.capacity} {tr('residents','只居民')}</p></div>
 {alerts.length?<div className="alert-list">{alerts.map(a=><article key={a.key} data-critical={a.critical}><details className="alert-residents"><summary><b>{a.critical?tr('Critical','危急'):tr('Warning','警告')} · {tr(...labels[a.key])}{a.count!==undefined?` (${a.count})`:''}</b><span>{tr('View residents','查看居民')}</span></summary><p>{alertAdvice(a.key)}</p>{['hunger','thirst','cold','hot','capacity','declining'].includes(a.key)&&<p>{tr('Colony-wide alert. Select a resident to inspect their condition.','全种群警报。选择居民查看个体状况。')}</p>}<div className="alert-rat-list">{alertResidents(world,a.key,m).map(r=><button key={r.id} onClick={()=>{useStore.getState().focus(r.id);setTab('rat');}}><span>{r.name}</span><small>{a.key==='dehydrated'?`${tr('Hydration','水合水平')} ${Math.round((r.wellbeing?.hydration??1)*100)}%`:tr('View rat →','查看个体 →')}</small></button>)}</div>{alertResidents(world,a.key,m).length===0&&<p>{tr('No living residents currently match this alert.','当前没有符合此警报的存活居民。')}</p>}{a.key==='extinct'&&<button onClick={()=>setTab('memorial')}>{tr('Open Memorial','打开纪念页')}</button>}</details></article>)}</div>:<div className="attention-note"><b>{tr('No active alerts','无当前警报')}</b><p>{tr('Monitor resources, social contact and access to shelter.','关注资源、社交接触和庇护空间。')}</p></div>}
 <details className="readout-details"><summary>{tr('Population & token details','种群与代币详情')}</summary><Hud/></details>
 <div className="section-caption">{tr('Needs','需求')}<span>{tr('Simulation indices 0–100. Lower is better.','模拟指数0–100，越低越好。')}</span></div>
 <div className="condition-grid">{['hunger','thirst','cold','hot','stress','crowdPressure'].map(key=><Metric key={key} label={tr(...labels[key])} value={m[key as 'hunger']}/>)}</div>
 <div className="social-stats"><Stat label={tr('Occupancy','占用率')} value={`${Math.round(m.occupancy*100)}%`}/><Stat label={tr('At play','活动中')} value={m.playing}/><Stat label={tr('Conflicts / day','每日冲突')} value={m.conflicts}/></div>
 <details className="readout-details"><summary>{tr('Space and social life','空间与社交')}</summary><div className="condition-grid">{m.localZones.map((z,i)=><Metric occupancy key={z.name} label={`${i>=7?tr('Social den','社交洞穴')+' '+(i-6):i===6?tr('Courtyard','庭院'):i?tr('Chamber','区域')+' '+i:tr('Nest','巢穴')} (${z.count}/${z.capacity})`} value={Math.min(1,z.count/z.capacity)}/>)}</div><p className="model-note">{tr('Local crowding can rise even when total capacity remains available.','即使总容量尚有余量，局部区域也可能拥挤。')}</p><div className="social-stats"><Stat label={tr('Close pairs','近距离配对')} value={m.closePairs}/><Stat label={tr('In nest','在巢内')} value={`${Math.round(m.nest*100)}%`}/><Stat label={tr('Maternal care','母性照护')} value={m.nursing}/><Stat label={tr('Cohesion','凝聚度')} value={`${Math.round(m.cohesion*100)}%`}/><Stat label={tr('Isolation','孤立')} value={`${Math.round(m.isolation*100)}%`}/></div></details>
 <details className="readout-details"><summary>{tr('Stress history','压力历史')}</summary>{m.history.length>1?<svg viewBox="0 0 240 54" role="img" aria-label={tr('Colony stress history','种群压力历史')}><polyline fill="none" stroke="#ef7777" strokeWidth="2" points={m.history.map((p,i)=>`${i*240/Math.max(1,m.history.length-1)},${50-p.stress*46}`).join(' ')}/></svg>:<p className="model-note">{tr('History builds as the simulation runs.','历史记录随模拟运行逐步生成。')}</p>}</details>
 <details className="readout-details"><summary>{tr('Compare environments','比较环境')}</summary><HabitatComparison/></details>
 <details className="readout-details"><summary>{tr('Behaviour and research','行为与研究')}</summary><p className="model-note">{tr('Social contact, shelter, exploration, gnawing and rest matter for rat welfare. This colony models proximity, affinity, play, shelter use and injury recovery.','社交接触、庇护、探索、啃咬和休息对大鼠福利很重要。本模拟包含邻近关系、亲和度、玩耍、庇护使用和伤势恢复。')}</p><a href="https://nc3rs.org.uk/3rs-resources/housing-and-husbandry-rat" target="_blank" rel="noreferrer">NC3Rs · {tr('Housing and husbandry','饲养与照护')}</a><p className="model-note">{tr('Facial pain scales require trained assessment. Blinking and our injury index are not a validated pain scale.','面部疼痛量表需要受过培训的评估。眨眼动画和本模拟的伤势指数不是经过验证的疼痛量表。')}</p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3163602/" target="_blank" rel="noreferrer">{tr('The Rat Grimace Scale','大鼠面部表情疼痛量表')}</a></details>
 <p className="model-note">{tr('Model indicators, not clinical measurements. Warning ≥45; critical ≥75 for collective indices. Individual alerts use separate thresholds.','模型指标，并非临床测量。群体指数≥45为警告，≥75为危急。个体警报使用单独阈值。')}</p>
 </>}
 {tab==='rat'&&<>{rat?<><div className="specimen-heading"><span>{tr('Individual observation','个体观察')}</span><h2>{rat.name}</h2>{rat.caregiver&&<p className="caregiver-badge">◇ {tr('Recognized caregiver','已认可的照护者')}</p>}<p>{rat.sex==='F'?tr('Female','雌性'):tr('Male','雄性')} · {Math.max(0,(rat.deadAt??world.simDay)-rat.bornAt).toFixed(1)} {tr('days','天')} · {tr('Generation','世代')} {rat.gen}</p><strong>{rat.deadAt!==null?tr('Deceased — see Memorial','已故——请查看纪念页'):current?tr(...current):rat.exploration?.den!==undefined?tr('Visiting a shared den','正在使用共享洞穴'):Math.hypot(rat.vx,rat.vy)>.3?tr('Exploring','探索中'):rat.inNest?tr('In the nest','在巢内'):tr('Resting','休息中')}</strong></div>{rat.deadAt===null&&<><div className="social-stats"><Stat label={tr('Energy','能量')} value={`${Math.round(rat.energy*100)}%`}/><Stat label={tr('Hydration','水合水平')} value={rat.wellbeing?`${Math.round(rat.wellbeing.hydration*100)}%`:'—'}/><Stat label={tr('Health','健康')} value={`${Math.round((1-(rat.injury??0))*100)}%`}/></div><Metric label={tr('Isolation distress','孤立困扰')} value={rat.wellbeing?.isolationDistress??0}/><details className="readout-details"><summary>{tr('Individual affinities','个体亲和度')}</summary><div className="affinity-list">{bonds.length?bonds.map(({r,value})=><div key={r.id}><span>{r.name}</span><b className={value<-.15?'negative':value>.15?'positive':''}>{value<-.15?tr('Avoids','回避'):value>.15?tr('Affinity','亲近'):tr('Neutral','中立')} · {Math.round(value*100)}</b></div>):<p>{tr('No other residents to compare.','暂无其他居民可供比较。')}</p>}</div></details></>}</>:<div className="empty-readout"><h2>{tr('Meet a resident','认识一位居民')}</h2><p>{tr('Select a rat in the scene or resident list.','在场景或居民列表中选择一只大鼠。')}</p></div>}<RatCare key={focused??'none'}/></>}
 {tab==='memorial'&&<Memorial/>}
 {tab==='events'&&<><details className="readout-details" open><summary>{tr('Observed interactions','已记录的互动')}</summary><div className="event-list">{(world.ecology?.events??[]).length?(world.ecology?.events??[]).slice(-5).reverse().map((e,i)=><article key={`${e.day}-${i}`}><b>{e.kind==='care'?tr('Care','照护'):e.kind==='conflicts'?tr('Conflict','冲突'):tr('Sharing','分享')}</b><p>{world.rats[e.a]?.name??world.memorial?.[e.a]?.name??e.a} / {world.rats[e.b]?.name??world.memorial?.[e.b]?.name??e.b}</p><small>{tr('Day','第')} {e.day.toFixed(1)}{tr('','天')}</small></article>):<p className="model-note">{tr('No interactions recorded yet.','尚无互动记录。')}</p>}</div></details><div className="section-caption">{tr('Recent trades','近期交易')}<span>{tr('USD uses the fixed simulation reference.','美元金额采用模拟的固定参考汇率。')}</span></div><p className="model-note">{tr('Possible reactions, not guaranteed outcomes. Affinity, condition and cooldowns apply.','下列为可能反应，并非保证结果。受亲和度、状态和冷却时间限制。')}</p><div className="event-list">{trades.length?trades.slice(0,8).map(t=><article key={t.id}><div><b className={t.side==='buy'?'positive':'negative'}>{t.side==='buy'?tr('Buy','买入'):tr('Sell','卖出')}</b><strong>{t.usd.toLocaleString(locale(),{style:'currency',currency:'USD'})}</strong></div><small>{t.venue==='demo'?tr('Simulated','模拟'):t.venue==='curve'?tr('Pons curve','Pons曲线'):tr('Pool','流动性池')}</small><p>{t.backlog?tr('Historical record. No reaction applied.','历史记录，未触发反应。'):tradeEffect(t.usd,t.side)}</p></article>):<p className="empty-readout">{tr('Waiting for the first trade.','等待第一笔交易。')}</p>}</div></>}
 </div></div>;
}
function alertAdvice(key:string){return key==='dehydrated'||key==='thirst'?tr('Check water access and individual hydration.','检查饮水通道和个体水合水平。'):key==='injured'||key==='conflicts'?tr('Check affected rats, rival affinities and recovery.','查看受影响个体、敌对关系及恢复情况。'):key==='hunger'||key==='exhausted'?tr('Check food availability and individual energy.','检查食物供应和个体能量。'):key==='capacity'||key==='localCapacity'||key==='crowdPressure'?tr('Review occupied zones and access to shelter.','检查区域占用及庇护空间。'):key==='isolation'?tr('Check social contact and affinity. Distance alone does not diagnose distress.','检查社交接触和亲和度。距离本身不能诊断困扰。'):key==='extinct'?tr('No living rats remain. Their records are in Memorial.','已无存活个体，可在纪念页查看记录。'):tr('Inspect needs, shelter and affected residents.','检查需求、庇护及受影响的居民。');}
function tradeEffect(usd:number,side:string){const buy=side==='buy';return usd<50?tr('Light resource or alert effect; no trade animation.','轻微资源或警戒变化，无交易动画。'):usd<250?buy?tr('May encourage curiosity.','可能激发好奇心。'):tr('May increase vigilance and shelter seeking.','可能提高警戒并寻找庇护。'):usd<500?buy?tr('Favours exploration, play and approach.','促进探索、玩耍和接近。'):tr('May increase stress and reduce play.','可能增加压力并减少玩耍。'):usd<1000?buy?tr('Collective wellbeing pulse; positive interactions.','群体良好状态脉冲，促进积极互动。'):tr('Stress pulse; higher conflict chance.','压力脉冲，冲突概率上升。'):buy?tr('Chance of courtship between eligible adults with positive affinity.','亲和度良好的适龄成年个体可能求偶。'):tr('Chance of a fight between adult rivals, with mild injury.','敌对成年个体可能争斗并产生轻伤。');}
function Metric({label,value,occupancy=false}:{label:string;value:number;occupancy?:boolean}){const pct=Math.max(0,Math.min(100,Math.round(value*100))),level=pct>=(occupancy?100:75)?'critical':pct>=(occupancy?70:45)?'warning':'good';return <div className="condition-metric" data-level={level}><div><span>{label}</span><b>{pct}{occupancy?'%':''}</b></div><div className="bar-track" role="meter" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={pct}><i style={{width:`${pct}%`}}/></div><small>{occupancy?(level==='critical'?tr('At capacity','已满'):level==='warning'?tr('High occupancy','占用率较高'):tr('Space available','空间充足')):level==='critical'?tr('Critical','危急'):level==='warning'?tr('Warning','警告'):tr('Low','低')}</small></div>}
function Stat({label,value}:{label:string;value:number|string}){return <div><b>{value}</b><span>{label}</span></div>}
