import {tr} from '../i18n';
import {useEffect,useRef,useState} from 'react';
import {getWorld} from '../store';
import type {Comparison} from '../sim/habitatComparison';
export default function HabitatComparison(){
 const worker=useRef<Worker|null>(null),[busy,setBusy]=useState(false),[result,setResult]=useState<Comparison|null>(null),[error,setError]=useState('');
 useEffect(()=>()=>worker.current?.terminate(),[]);
 function run(){worker.current?.terminate();setBusy(true);setError('');try{const w=new Worker(new URL('../sim/habitatComparison.worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{setBusy(false);if(e.data.error)setError(e.data.error);else setResult(e.data.result);w.terminate();worker.current=null;};w.onerror=()=>{setError(tr('Comparison failed. Retry.','比较失败，请重试。'));setBusy(false);w.terminate();worker.current=null;};w.postMessage(getWorld());}catch{setBusy(false);setError(tr('Comparison unavailable.','比较不可用。'));}}
 return <section className="habitat-experiment"><div className="panel-head"><span>{tr('Environment experiment','环境实验')}</span></div><p className="model-note">{tr('Two copies of this colony, 2 days, identical trades. Basic: water at the nest, no play. Enriched: distributed water and activities.','同一种群的两个副本运行2天，交易相同。基础环境：巢内供水、无玩耍设施。丰富环境：分布式供水与活动设施。')}</p><button onClick={run} disabled={busy}>{busy?tr('Comparing…','比较中…'):tr('Compare environments','比较环境')}</button>{busy&&<button onClick={()=>{worker.current?.terminate();worker.current=null;setBusy(false);}}>{tr('Cancel','取消')}</button>}{error&&<p role="alert">{error}</p>}{result&&<><p className="model-note">{tr('Started with ','初始数量 ')}{result.initialPopulation}{tr(' rats · ','只大鼠 · ')}{result.days.toFixed(1)}{tr(' simulated days. Model comparison, not a scientific prediction.','个模拟日。模型比较，并非科学预测。')}</p><table style={{width:'100%',fontSize:11}}><thead><tr><th>{tr('Habitat','环境')}</th><th>{tr('Stress*','压力*')}</th><th>{tr('Thirst*','缺水*')}</th><th>{tr('Alive','存活')}</th><th>{tr('Born / died','出生／死亡')}</th></tr></thead><tbody>{result.results.map(r=><tr key={r.mode}><td>{r.mode==='basic'?tr('Basic','基础'):tr('Enriched','丰富')}</td><td>{Math.round(r.stress*100)}%</td><td>{Math.round(r.thirst*100)}%</td><td>{r.alive}</td><td>{r.births} / {r.deaths}</td></tr>)}</tbody></table><p className="model-note">{tr('*Stress averaged over living rats and time; thirst is the share of low-hydration observations.','*压力为存活个体随时间的平均值；缺水为低水合水平观察值所占比例。')}</p></>}</section>;
}
