import {useState} from 'react';
import {getWorld} from '../store';
import {tr,locale} from '../i18n';
export function causeLabel(c:string){const labels:Record<string,[string,string]>={age:['Old age','衰老'],starvation:['Starvation','饥饿'],cold:['Cold exposure','寒冷'],neonatal_abandon:['Neonatal abandonment','幼崽被遗弃'],neonatal_cannibal:['Neonatal cannibalism','幼崽被同类吞食'],stillbirth:['Stillbirth','死产'],crowding:['Overcrowding','过度拥挤'],none:['Not recorded','未记录']};return tr(...(labels[c]??labels.none));}
export default function Memorial(){const world=getWorld();const [selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState('');
 const records={...Object.fromEntries(Object.values(world.rats).filter(r=>r.deadAt!==null).map(r=>[r.id,r])),...world.memorial};
 const dead=Object.values(records).sort((a,b)=>(b.deadAt??0)-(a.deadAt??0)||a.id.localeCompare(b.id));const rat=selected?records[selected]:undefined;
 const filtered=dead.filter(r=>r.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <section className="memorial"><h2>{tr('In memory','纪念')}</h2><p>{dead.length.toLocaleString(locale())} {tr('recorded lives','份生命记录')}</p>{world.totals.deaths>dead.length&&<p className="model-note">{tr('Some older records are unavailable in this saved colony.','此存档中部分早期记录不可用。')}</p>}
 {!dead.length?<p>{tr('No deaths have been recorded.','尚无死亡记录。')}</p>:<><label className="memorial-search">{tr('Find a name','搜索名字')}<input value={query} onChange={e=>setQuery(e.target.value)}/></label>
 {rat&&<article className="memorial-record" aria-live="polite"><h3>{rat.name}</h3>{rat.caregiver&&<p>◇ {tr('Recognized caregiver','已认可的照护者')}{rat.residenceDays?' · '+rat.residenceDays+'d':''}</p>}<dl><dt>{tr('Age at death','死亡时年龄')}</dt><dd>{Math.max(0,(rat.deadAt??world.simDay)-rat.bornAt).toFixed(1)} {tr('days','天')}</dd><dt>{tr('Recorded cause','记录的死因')}</dt><dd>{causeLabel(rat.deathCause)}</dd><dt>{tr('Death day','死亡日')}</dt><dd>{rat.deadAt?.toFixed(1)}</dd><dt>{tr('Sex / generation','性别／世代')}</dt><dd>{rat.sex==='F'?tr('Female','雌性'):tr('Male','雄性')} / {rat.gen}</dd><dt>{tr('Parents','父母')}</dt><dd>{[rat.motherId,rat.fatherId].map(id=>id?(world.rats[id]?.name??records[id]?.name??id):rat.gen===0?tr('Founder','创始成员'):tr('Unknown','未知')).join(' / ')}</dd><dt>{tr('Recorded offspring','记录的子代数')}</dt><dd>{rat.offspring}</dd></dl><p>{tr('A historical record. Care actions are unavailable.','这是历史记录，无法进行照护操作。')}</p></article>}
 <div className="grave-grid">{filtered.slice(0,120).map(r=><button key={r.id} className="grave" aria-pressed={r.id===selected} onClick={()=>setSelected(r.id)}><span aria-hidden="true" className="grave-mark">✦</span><strong>{r.name}</strong><small>{tr('Day','第')} {r.deadAt?.toFixed(1)} {tr('','天')}</small><small>{causeLabel(r.deathCause)}</small></button>)}</div>{!filtered.length&&<p>{tr('No matching names.','没有匹配的名字。')}</p>}{filtered.length>120&&<p>{tr('Showing the latest 120 matches. Search a name to find older records.','显示最近的120条匹配记录。搜索名字可查找更早的记录。')}</p>}</>}
 </section>;
}
