import PaidCare from './PaidCare';
import {mainnetPayments} from '../paymentMode';
import {useWallet,stagingSignIn} from '../wallet';
import {useState} from 'react';
import {getWorld,useStore} from '../store';
import {tr,locale} from '../i18n';
import {CARE_RULES,DEMO_WALLETS,demoCare,type CareAction} from '../sim/care';
const labels:Record<CareAction,[string,string]>={mint:['Mint rat','铸造大鼠'],name:['Rename','重命名'],feed:['Feed','喂食'],water:['Offer water','提供饮水'],pet:['Pet','抚摸'],play:['Play','玩耍'],treat:['Offer treat','提供零食'],explore:['Invite to explore','邀请探索'],prosocial:['Sociability booster','社交增强剂'],aggression:['Irritability booster','易怒增强剂']};
export default function RatCare(){
 const connected=useWallet(s=>s.account),authenticated=useWallet(s=>s.authenticated);
 const version=useStore(s=>s.version);void version;const focused=useStore(s=>s.focusedId),status=useStore(s=>s.feedStatus),world=getWorld();
 const [wallet,setWallet]=useState<string>(DEMO_WALLETS[0]),[name,setName]=useState(''),[message,setMessage]=useState<[string,string]|null>(null);
 const rat=focused?world.rats[focused]:undefined;
 if(mainnetPayments)return <PaidCare ratId={focused}/>;
 if(!rat||rat.deadAt!==null)return null;
 const owner=world.care?.owners[rat.id],demo=status==='demo',allowed=demo&&(!owner||owner===wallet);
 function act(action:CareAction){try{if(useStore.getState().feedStatus!=='demo')throw Error('Payments unavailable');demoCare(getWorld(),wallet,rat!.id,action,Date.now(),name||rat!.name);setMessage(['Action completed. Test tokens burned.','操作完成，测试代币已销毁。']);useStore.setState(s=>({version:s.version+1}));}catch(e){const errors:Record<string,[string,string]>={'Only owner may interact':['Only the owner can interact.','仅所有者可互动。'],'Cooldown active':['This action is cooling down.','此操作处于冷却期。'],'Already satiated':['This rat is already satiated.','这只大鼠已经吃饱。'],'Rat busy or needs rest':['This rat is busy or needs rest.','这只大鼠正忙或需要休息。'],'Invalid name':['Enter a valid name (1–24 characters).','请输入有效名字（1–24个字符）。'],'Insufficient test tokens':['Not enough test tokens.','测试代币不足。'],'Water unavailable or not needed':['Water is unavailable or not needed now.','当前无法提供饮水或无需饮水。'],'Adults only':['Adults only.','仅适用于成年个体。'],'No acute stress to relieve':['No acute stress to relieve.','暂无需要缓解的急性压力。']};setMessage(errors[(e as Error).message]??['Action unavailable. Check ownership, needs and cooldown.','操作不可用，请检查所有权、需求和冷却时间。']);}}
 return <section className="rat-care"><div className="panel-head"><span>{tr('Individual care','个体照护')}</span><span>{tr('Observation is always public','观察始终向所有人开放')}</span></div><p>{owner?`${tr('Owner','所有者')}: ${owner.slice(0,6)}…${owner.slice(-4)}`:tr('Not minted: any wallet may interact.','尚未铸造：任何钱包均可互动。')}</p>
 {stagingSignIn&&<div className="wallet-scope"><strong>{tr('Persistent wallet account','持久化钱包账户')}</strong><p>{authenticated?tr('Signed in. Paid interactions await a validated testnet token and the authoritative colony connection.','已登录。付费互动仍需验证测试网代币并连接权威群落服务。'):tr('Connect and sign in to verify your wallet. The demonstration below stays separate from your account.','连接并登录以验证您的钱包。下方演示与您的账户相互独立。')}</p><button className="chip" onClick={()=>useWallet.setState({open:true})}>{tr('Open wallet account','打开钱包账户')}</button></div>}
 {demo?<><p className="demo-notice"><b>{tr('Demonstration mode','演示模式')}</b><br/>{tr('Fictional tokens. No real transaction.','虚拟测试代币，无真实交易。')}</p><label>{tr('Test account','测试账户')}<select value={wallet} onChange={e=>setWallet(e.target.value)}><option value={DEMO_WALLETS[0]}>A</option><option value={DEMO_WALLETS[1]}>B</option></select></label><p>{tr('Balance','余额')}: {(world.demoToken?.balances[wallet]??5000000).toLocaleString(locale())}<br/>{tr('Burned','已销毁')}: {(world.care?.burned??0).toLocaleString(locale())}</p></>:<div><button className="chip" onClick={()=>useWallet.setState({open:true})}>{connected?tr('View connected wallet','查看已连接钱包'):tr('Connect wallet','连接钱包')}</button><p>{tr('Paid care awaits the RATTERY token and payment service.','付费照护尚待RATTERY代币和支付服务配置完成。')}</p></div>}
 {demo&&owner&&owner!==wallet&&<p className="permission-note">{tr('Only the owner can provide care. Observation stays public.','仅所有者可以照护，观察仍向所有人开放。')}</p>}<label>{tr('Name','名字')}<input aria-label={tr('Rat name','大鼠名字')} maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder={rat.name}/></label>
 <div className="care-actions">{(Object.keys(CARE_RULES) as CareAction[]).filter(a=>owner?a!=='mint':a!=='name').map(action=>{const rule=CARE_RULES[action],key=rat.id+':'+(['prosocial','aggression'].includes(action)?'stimulus':action),remaining=Math.max(0,(world.care?.cooldowns[key]??0)-Date.now());return <button className="chip" key={action} disabled={!allowed||remaining>0} onClick={()=>act(action)} title={`${tr('Cooldown','冷却时间')}: ${rule.hours} ${tr('real hours','现实小时')}`}><span>{tr(...labels[action])}</span><small>{rule.cost.toLocaleString(locale())} {tr('tokens','代币')}{remaining>0?` · ${Math.ceil(remaining/60000)} ${tr('min','分钟')}`:''}</small></button>;})}</div><p role="status">{message&&tr(...message)}</p><p>{tr('Boosters are fictional simulation effects for adult rats. Each burns 100,000 RATTERY and biases social interactions for 2 real hours. Only one can be active; both share the same cooldown. Encounters still depend on proximity and affinity.','增强剂是仅适用于成年大鼠的虚构模拟效果。每次销毁100,000枚RATTERY，并在现实2小时内影响社交互动。两种效果不可同时启用，且共享冷却时间。互动仍取决于距离和亲和度。')}</p><p>{tr('100% burned. Cooldowns apply per rat and action; stimuli share a 2-hour cooldown.','100%销毁。冷却时间按个体和操作计算；两种刺激共享2小时冷却时间。')}</p></section>;
}
