import {useSeasonClosed} from '../season/resultState';
import {useCallback,useEffect,useState,useRef} from 'react';
import {createPortal} from 'react-dom';
import {formatUnits} from 'ethers';
import {tr,useLanguage} from '../i18n';
import {useWallet,seasonTransactionRequest,seasonWalletFunding} from '../wallet';
import {useSeason,seasonAPI,refreshSeason,ROUTER,SIGNER} from '../seasonState';
import {seasonApprovalCall,seasonBurnCall,type SeasonQuote} from '../market/seasonBurn';
const names=[['Join a nest','加入巢穴'],['Feed','喂养'],['Shield','护盾'],['Attack','攻击']] as const;
type Funding={balance:string;allowance:string};type Pending={quoteHash:string;hash:string};
function hydrate(raw:any):SeasonQuote{const q={...raw};for(const k of ['nonce','membership','amount','usdCents','issuedAt','expiresAt'])q[k]=BigInt(q[k]);return q;}
const amount=(value:string)=>Number(formatUnits(value,18)).toLocaleString(undefined,{maximumFractionDigits:4});
function savedAction(owner:string|null):Pending|null{try{const p=JSON.parse(localStorage.getItem('rattery:season-pending:'+owner)||'null');return p&&/^0x[0-9a-f]{64}$/i.test(p.quoteHash)&&/^0x[0-9a-f]{64}$/i.test(p.hash)?p:null;}catch{return null;}}
function saveAction(owner:string,pending:Pending|null){try{if(pending)localStorage.setItem('rattery:season-pending:'+owner,JSON.stringify(pending));else localStorage.removeItem('rattery:season-pending:'+owner);}catch{/* Receipt stays in the open dialog even if storage is unavailable. */}}
export default function SeasonAction(){
 const closed=useSeasonClosed();useLanguage(s=>s.language);const {snapshot,action,available}=useSeason(),wallet=useWallet(),dialog=useRef<HTMLDivElement>(null),lock=useRef(false),checking=useRef(false);
 const [nest,setNest]=useState(1),[intent,setIntent]=useState<any>(null),[funding,setFunding]=useState<Funding|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[hash,setHash]=useState(''),[pending,setPending]=useState<Pending|null>(null),[confirmed,setConfirmed]=useState(false),[approvalSent,setApprovalSent]=useState(false),[now,setNow]=useState(Date.now());
 const pendingRef=useRef(pending);pendingRef.current=pending;
 const close=()=>{if(!lock.current)useSeason.setState({action:null});};
 useEffect(()=>{const saved=savedAction(wallet.account);setIntent(null);setFunding(null);setNotice('');setHash(saved?.hash??'');setPending(saved);setConfirmed(false);setApprovalSent(false);setNest(action===1||action===2?snapshot?.member?.nest||1:action===3&&snapshot?.member?.nest===1?2:1);},[action,wallet.account]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const checkPending=useCallback(async()=>{
  const submitted=pendingRef.current,owner=wallet.account;if(!submitted||!owner||checking.current)return;checking.current=true;
  try{const result=await seasonAPI('finalize',submitted);if(useWallet.getState().account!==owner||pendingRef.current?.hash!==submitted.hash)return;
   if(result.confirmed){saveAction(owner,null);setPending(null);setConfirmed(true);setIntent(null);setNotice(tr('Confirmed. Your nest score is recorded onchain.','已确认。巢穴积分已记录在链上。'));void refreshSeason();}
   else if(result.status==='reverted'){saveAction(owner,null);setPending(null);setIntent(null);setFunding(null);setApprovalSent(false);const reason=result.reason==='INSUFFICIENT_RATTERY'?tr(`Not enough RATTERY: the transaction had ${amount(result.balance)} available and needed ${amount(result.required)}. No RATTERY was burned; gas was spent.`,`RATTERY余额不足：可用 ${amount(result.balance)}，需要 ${amount(result.required)}。未销毁RATTERY，但已消耗gas。`):result.reason==='APPROVAL_REQUIRED'?tr('The allowance was too low. No RATTERY was burned. Get a new quote and approve its amount.','授权额度不足。未销毁RATTERY。请获取新报价并授权。'):result.reason==='QUOTE_EXPIRED'?tr('The quote expired before execution. No RATTERY was burned. Get a new quote.','报价在执行前过期。未销毁RATTERY，请重新获取报价。'):tr('The transaction reverted. No RATTERY was burned. Refresh the quote before trying again.','交易已回滚，未销毁RATTERY。重试前请刷新报价。');setNotice(reason);void refreshSeason();}
   else setNotice(tr('Transaction submitted. Waiting for blockchain confirmations.','交易已提交，正在等待区块链确认。'));
  }catch(error){if(useWallet.getState().account===owner)setNotice((error as Error).message);}finally{checking.current=false;}
 },[wallet.account]);
 useEffect(()=>{if(!pending||!wallet.authenticated)return;void checkPending();const timer=setInterval(()=>void checkPending(),5000);return()=>clearInterval(timer);},[pending?.hash,wallet.authenticated,checkPending]);
 useEffect(()=>{if(!intent||!wallet.account||pending)return;let active=true;const owner=wallet.account;const refresh=async()=>{try{const f=await seasonWalletFunding(owner,ROUTER);if(active)setFunding(f);}catch{/* Keep the server observation; execution checks again before sending. */}};void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>{active=false;clearInterval(timer);};},[intent,wallet.account,!!pending]);
 useEffect(()=>{if(action===null)return;const previous=document.activeElement as HTMLElement|null;dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!lock.current){e.stopImmediatePropagation();useSeason.setState({action:null});}if(e.key==='Tab'){const items=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]')??[]),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',key,true);return()=>{window.removeEventListener('keydown',key,true);if(previous?.isConnected)previous.focus();};},[action]);
 if(action===null)return null;
 const ready=!closed&&wallet.authenticated&&snapshot?.phase==='open'&&available,active=!!intent&&Number(intent.quote.expiresAt)*1000>now+3000;
 const funded=!!intent&&!!funding&&BigInt(funding.balance)>=BigInt(intent.quote.amount),approved=!!intent&&!!funding&&BigInt(funding.allowance)>=BigInt(intent.quote.amount);
 const step=(current:boolean,complete=false)=>'season-step'+(complete?' is-complete':current?' is-current':'');
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{await work();}catch(e){setNotice((e as any)?.code===4001?tr('Request canceled in your wallet.','已在钱包中取消请求。'):(e as Error).message||tr('Wallet verification failed. Refresh the quote.','钱包验证失败，请刷新报价。'));}finally{setBusy(false);lock.current=false;void refreshSeason();}}
 const validate=(i:any)=>{if(i.config.router.toLowerCase()!==ROUTER||i.config.quoteSigner.toLowerCase()!==SIGNER||i.config.token.toLowerCase()!=='0xc322305e79337300b59ff48389f8c9a1d9e0de76'||i.quote.wallet.toLowerCase()!==wallet.account||i.quote.kind!==action||i.quote.nest!==nest)throw Error('Unexpected quote');return hydrate(i.quote);};
 const getQuote=()=>run(async()=>{const i=await seasonAPI('quote',{kind:action,nest});const q=validate(i);seasonBurnCall(i.config,q,i.signature);setIntent(i);setFunding(i.funding??null);setApprovalSent(false);setHash('');setConfirmed(false);});
 const checkFunding=async(q:SeasonQuote)=>{const f=await seasonWalletFunding(wallet.account!,ROUTER);setFunding(f);if(BigInt(f.balance)<q.amount)throw Error(tr(`Not enough RATTERY. Available: ${amount(f.balance)}; required: ${amount(String(q.amount))}. No transaction was sent.`,`RATTERY余额不足。可用：${amount(f.balance)}；需要：${amount(String(q.amount))}。未发送交易。`));return f;};
 const approve=()=>run(async()=>{if(closed)throw Error("Season I has ended.");if(!active)throw Error('Quote expired. Get a new quote.');const q=validate(intent);await checkFunding(q);await seasonTransactionRequest(wallet.account!,seasonApprovalCall(intent.config,q),true);setApprovalSent(true);setNotice(tr('Approval submitted. The next button turns gold when it is confirmed.','授权已提交，确认后下一步按钮会变为金色。'));});
 const execute=()=>run(async()=>{if(closed)throw Error("Season I has ended.");if(!active||Number(intent.quote.expiresAt)*1000<Date.now()+10000)throw Error(tr('Quote is expiring. Get a new quote before executing.','报价即将过期，请获取新报价后执行。'));const q=validate(intent),f=await checkFunding(q);if(BigInt(f.allowance)<q.amount)throw Error(tr('Wait for the approval to confirm first.','请先等待授权确认。'));const tx=seasonBurnCall(intent.config,q,intent.signature);const h=String(await seasonTransactionRequest(wallet.account!,tx,true)),submitted={quoteHash:intent.quoteHash,hash:h};saveAction(wallet.account!,submitted);setHash(h);setPending(submitted);setNotice(tr('Transaction submitted. Checking confirmations automatically…','交易已提交，正在自动检查确认…'));});
 return createPortal(<div className="stock-popup-backdrop"><div ref={dialog} className="stock-popup season-action-dialog" role="dialog" aria-modal="true" aria-labelledby="season-action-title"><header><h2 id="season-action-title">{tr(names[action][0],names[action][1])}</h2><button className="stock-popup-close" disabled={busy} onClick={close} aria-label={tr('Close','关闭')}>×</button></header>
 <p className="season-action-phase">{closed?tr('Season I ended. New actions are closed.','第一赛季已结束，操作已关闭。'):available&&snapshot?.phase==='open'?tr('● Season open · follow the gold button','● 赛季已开启 · 请按金色按钮操作'):snapshot?.phase==='updating'?tr('Updating scores — please wait a moment','正在更新积分，请稍候'):tr('Checking Season availability…','正在检查赛季状态…')}</p>
 {!wallet.authenticated?<p><button className="season-step is-current" onClick={()=>{close();useWallet.setState({open:true});}}>{tr('Connect and sign in','连接并登录')}</button></p>:<>
 <div className="season-nest-choice">{['NVDA','AAPL','AMZN'].map((ticker,i)=><button key={ticker} disabled={busy||!!pending||confirmed||action===3&&snapshot?.member?.nest===i+1||(action===1||action===2)&&snapshot?.member?.nest!==i+1} aria-pressed={nest===i+1} onClick={()=>{setNest(i+1);setIntent(null);setFunding(null);setApprovalSent(false);}}>{ticker}<small>{snapshot?.nests[i]?`${snapshot.nests[i].score}${snapshot.nests[i].halfPoint?'.5':''} pts`:''}</small></button>)}</div>
 <p>{tr('The action burns RATTERY. Review the amount and gas in your wallet.','此操作将销毁 RATTERY。请在钱包中核对数量与 gas 费用。')}</p>
 <button className={step(!active&&!pending&&!confirmed,active||confirmed)} disabled={!ready||busy||!!pending||confirmed} onClick={getQuote}>{tr('Get current quote','获取当前报价')}</button>
 {intent&&<div className="season-quote-review"><strong>{Number(intent.quote.usdCents)/100} USD · {amount(intent.quote.amount)} RATTERY</strong><p>{active?`${Math.max(0,Math.floor((Number(intent.quote.expiresAt)*1000-now)/1000))}s`:tr('Quote expired. Refresh it.','报价已过期，请刷新。')}</p>
 {funding&&<p className={funded?'season-balance':'season-balance is-short'}>{tr('Available','可用')}: {amount(funding.balance)} RATTERY{!funded&&<strong> · {tr('Insufficient balance — no burn will be sent','余额不足，不会发送销毁交易')}</strong>}</p>}
 <button className={step(active&&funded&&!approved&&!pending,approved)} disabled={!ready||!active||!funded||busy||!!pending||approved||approvalSent} onClick={approve}>{tr('1 · Approve exact amount','1 · 授权指定数量')}</button><button className={step(active&&funded&&approved&&!pending,!!pending||confirmed)} disabled={!ready||!active||!funded||!approved||busy||!!pending} onClick={execute}>{tr('2 · Burn & execute','2 · 销毁并执行')}</button></div>}
 <p><button className={step(!!pending,confirmed)} disabled={busy||!pending} onClick={()=>void checkPending()}>{confirmed?tr('Confirmed ✓','已确认 ✓'):tr('Check submitted action','检查已提交操作')}</button></p></>}
 {busy&&<p role="status">{tr('Waiting for wallet or confirmation…','等待钱包或确认…')}</p>}{notice&&<p role="status">{notice}</p>}{hash&&<a href={`https://robin.etherscan.io/tx/${hash}`} target="_blank" rel="noopener noreferrer">{tr('View transaction','查看交易')} ↗</a>}
 </div></div>,document.body);
}

