import {useEffect,useState} from 'react';
import {keccak256} from 'ethers';
import WalletConnection from './WalletConnection';
import {useWallet,seasonTransactionRequest} from '../wallet';
type Plan={chainId:number;operator:string;quoteSigner:string;opening:string;closing:string;dataHash:string;transaction:{data:string;value:string}};
export default function SeasonSetup(){
 const wallet=useWallet(),[plan,setPlan]=useState<Plan|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[hash,setHash]=useState(''),[gas,setGas]=useState('');
 useEffect(()=>{fetch('/season/season1-deploy.json').then(r=>{if(!r.ok)throw Error('Deployment plan unavailable');return r.json();}).then(p=>{if(p.chainId!==4663||p.operator.toLowerCase()!=='0xd40ed0214353b746fd567fa4a57409d1b5709988'||keccak256(p.transaction.data)!==p.dataHash||p.transaction.value!=='0x0')throw Error('Invalid deployment plan');setPlan(p);}).catch(e=>setError(e.message));},[]);
 const ready=plan&&wallet.account===plan.operator.toLowerCase()&&wallet.chainId==='0x1237'&&!busy&&!hash;
 async function submit(send:boolean){if(!plan||!ready)return;setError('');setBusy(true);try{if(Date.now()>=Date.parse(plan.opening))throw Error('The opening time has passed. A new launch plan is required.');const result=await seasonTransactionRequest(plan.operator,plan.transaction,send);if(typeof result!=='string')throw Error('Invalid wallet response');if(send){setHash(result);localStorage.setItem('rattery:season1-deployment',result);}else setGas(BigInt(result).toString());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="stock-popup" style={{margin:'32px auto',maxWidth:780,maxHeight:'none'}}><WalletConnection/><h2>Season I · Operator setup</h2><p>Deploy the action contract on Robinhood Chain. This transaction creates the contract; it does not transfer RATTERY or the prize fund. Only ETH gas is paid.</p>
 {plan&&<><p>Operator / treasury: <code style={{wordBreak:'break-all'}}>{plan.operator}</code></p><p>Scheduled opening: <b>28 September 2026 · 13:00 São Paulo</b><br/>Action closing: <b>5 October 2026 · 00:00 São Paulo</b></p><p>Actions: join, feed, shield and attack. Burns are atomic. The service signs 60-second quotes and posts colony score updates every ten minutes. The operator can pause the contract.</p><p>Service signer: <code style={{wordBreak:'break-all'}}>{plan.quoteSigner}</code></p><p>Deployment data hash: <code style={{wordBreak:'break-all'}}>{plan.dataHash}</code></p><p>The competition remains unavailable until the deployed contract and the backend are verified. Prize swaps and distributions are not part of this contract.</p>
 <button disabled={!ready} onClick={()=>void submit(false)}>Estimate deployment gas</button>{gas&&<p>Gas estimate: {gas} units. Review the ETH fee in your wallet.</p>}<button disabled={!ready||!gas} onClick={()=>void submit(true)}>Review deployment in wallet</button></>}
 {busy&&<p role="status">Waiting for wallet…</p>}{error&&<p role="alert">{error}</p>}{hash&&<p>Deployment submitted: <a href={`https://robin.etherscan.io/tx/${hash}`} target="_blank" rel="noopener noreferrer">{hash}</a><br/>Send this transaction hash to Astra for verification.</p>}</main>;
}