const {chromium}=require('./lib/browser-runtime.cjs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5187/?view=mating-studio');await page.waitForSelector('#mating-studio[data-ready="true"]');
const result=await page.evaluate(async()=>{
const T=await import('/node_modules/three/build/three.module.js'),{BlenderRatAssets}=await import('/src/render/BlenderRat.ts'),{encounterPose}=await import('/src/sim/pairEncounter.ts');const assets=await BlenderRatAssets.load();let minTail=Infinity,headClear=Infinity,maxHip=0;const results=[];
for(const fps of [30,60,120]){const rat=assets.create('mating-adult-male'),scene=new T.Scene();scene.add(rat.root);let pelvis,skin;rat.root.traverse(o=>{if(o.name==='pelvis')pelvis=o;if(o.isSkinnedMesh&&o.name==='Warm_pink_skin')skin=o});const rest=pelvis.quaternion.clone(),pos=skin.geometry.attributes.position,tail=[];for(let i=0;i<pos.count;i++)if(pos.getX(i)<-1.1)tail.push(i);
for(let i=0;i<=16*fps;i++){const t=i/fps,p=encounterPose(t);rat.root.position.set(.5+p.x,p.y,p.z);rat.root.rotation.z=p.pitch;rat.update(1/fps,4,t<3||t>12,.18,false,i===0,true,false,true,()=>0,t<3||t>12,false,false,{blend:p.lift,frontHeight:p.frontHeight,rhythm:p.rhythm});rat.root.updateMatrixWorld(true);
if(t>6&&t<9)maxHip=Math.max(maxHip,rest.angleTo(pelvis.quaternion));
if(i%Math.max(1,Math.round(fps/15))===0){skin.skeleton.update();for(const index of tail.filter((_,j)=>j%8===0)){const v=new T.Vector3().fromBufferAttribute(pos,index);skin.applyBoneTransform(index,v);v.applyMatrix4(skin.matrixWorld);minTail=Math.min(minTail,v.y);}const head=rat.root.getObjectByName('head').getWorldPosition(new T.Vector3());if(p.close>.5)headClear=Math.min(headClear,head.y);}
for(const value of [...rat.root.position.toArray(),...pelvis.quaternion.toArray()])if(!Number.isFinite(value))throw Error('Invalid transform');
}results.push(fps);rat.dispose();}assets.dispose();return {results,minTail,headClear,maxHip};});
console.log(result);assert(result.minTail>-.03);assert(result.headClear>.7);assert(result.maxHip>.025);assert.deepEqual(errors,[]);await page.getByRole('button',{name:'Mating posture',exact:true}).click();await page.screenshot({path:'test-results/encounter-revised.png'});console.log('PASS: skinned tail clearance, elevated head, articulated pelvis, full cycle at 30/60/120 FPS, no page errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
