import assert from 'node:assert/strict';
import {once} from 'node:events';
import {observerServer} from '../server/observer';
import handler from '../api/observer';
let reads=0,now=100000,fail=false;const secret='a'.repeat(64),snapshot={protocol:1,colonyId:'rattery-staging-market-v1',revision:1,at:now,world:{rats:{}},paymentsEnabled:false};
const server=observerServer(async()=>{reads++;await new Promise(r=>setTimeout(r,20));if(fail)throw Error('PRIVATE_DATABASE_URL');return snapshot;},secret,()=>now);server.listen(0,'127.0.0.1');await once(server,'listening');const port=(server.address() as any).port,url=`http://127.0.0.1:${port}/snapshot`;
try{assert.equal((await fetch(url)).status,401);assert.equal(reads,0);assert.equal((await fetch(url,{method:'POST'})).status,405);const responses=await Promise.all(Array.from({length:12},()=>fetch(url,{headers:{Authorization:'Bearer '+secret}})));assert(responses.every(r=>r.status===200));assert.equal(reads,1,'Coalesce concurrent reads');now+=1000;fail=true;const bad=await fetch(url,{headers:{Authorization:'Bearer '+secret}});assert.equal(bad.status,503);assert(!(await bad.text()).includes('PRIVATE'));}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
const nativeFetch=globalThis.fetch;const env={...process.env};let called=0;
const invoke=async(method='GET')=>{let code=200,body:any;const headers:Record<string,string>={};await handler({method,query:{url:'https://evil.invalid'}},{setHeader:(k,v)=>{headers[k]=v;},status(n){code=n;return this;},json(v){body=v;},end(){}});return {code,body,headers};};
try{delete process.env.RATTERY_OBSERVER_ENABLED;assert.equal((await invoke()).code,503);process.env.VITE_STAGING='true';process.env.RATTERY_OBSERVER_ENABLED='true';process.env.RATTERY_OBSERVER_URL='https://observer.up.railway.app/snapshot';process.env.RATTERY_OBSERVER_SECRET=secret;globalThis.fetch=async(input,options)=>{called++;assert.equal(String(input),'https://observer.up.railway.app/snapshot');assert.equal((options?.headers as any).Authorization,'Bearer '+secret);return new Response(JSON.stringify(snapshot),{headers:{'Content-Type':'application/json'}});};assert.equal((await invoke()).code,200);assert.equal((await invoke('POST')).code,405);assert.equal(called,1);process.env.RATTERY_OBSERVER_URL='https://observer.up.railway.app.evil.invalid/snapshot';assert.equal((await invoke()).code,503);assert.equal(called,1);}finally{globalThis.fetch=nativeFetch;process.env=env;}
console.log('PASS: authenticated read-only route, cache single flight, opaque failures, staging gate, method/URL restrictions, secret stays server-side');
