import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {Wallet} from 'ethers';
import {StagingAuth,digest} from '../server/auth';
import {Persistence} from '../server/persistence';
import {stagingServer} from '../server/http';
import {createWorld} from '../src/sim/colony';
import {burnCall} from '../src/market/burn';
const connectionString=process.env.RATTERY_TEST_DATABASE_URL;
if(connectionString&&new URL(connectionString).search)throw Error('Test URL must not override verified TLS via query parameters');
const database=connectionString?decodeURIComponent(new URL(connectionString).pathname.slice(1)):process.env.PGDATABASE;
if(!database?.endsWith('_test'))throw Error('Use an isolated database ending in _test');
const connection=connectionString?{connectionString,ssl:{rejectUnauthorized:true}}:{};
const pool=new Pool({...connection,max:30});
const schema='test_'+randomUUID().replaceAll('-','');
await pool.query('CREATE SCHEMA '+schema);await pool.end();
const db=new Pool({...connection,max:30,options:'-c search_path='+schema+',public'});
let now=Math.floor(Date.now()/1000)*1000+123;
const chainId=process.env.RATTERY_TEST_CHAIN_ID==='4663'?4663:46630;
const origin=chainId===4663?'https://rattery.invalid':'https://staging.rattery.invalid';
const auth=new StagingAuth(db,origin,()=>now,chainId);
const a=Wallet.createRandom(),b=Wallet.createRandom();
const token='0x'+'a'.repeat(40),chainHash='0x'+'b'.repeat(64);
const burns=new Map<string,{wallet:string,amount:bigint,time:number}>();
let rpcDown=false;
const rpc=async(method:string,args:unknown[])=>{
 if(rpcDown)throw Error('RPC unavailable');
 if(method==='eth_call')return '0x'+(1_000_000_000n*10n**18n).toString(16);
 if(method==='eth_chainId')return '0x'+chainId.toString(16);
 if(method==='eth_blockNumber')return '0x78';
 if(method==='eth_getBlockByNumber')return {number:'0x64',hash:chainHash,timestamp:'0x'+Math.floor(now/1000).toString(16)};
 const hash=String(args[0]),entry=burns.get(hash);if(!entry)return null;
 const tx={hash,from:entry.wallet,to:token,input:burnCall(token,entry.amount).data,value:'0x0'};
 if(method==='eth_getTransactionByHash')return tx;
 if(method==='eth_getTransactionReceipt')return {transactionHash:hash,from:entry.wallet,to:token,status:'0x1',blockNumber:'0x64',blockHash:chainHash,logs:[{address:token,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+entry.wallet.slice(2).padStart(64,'0'),'0x'+'0'.repeat(64)],data:'0x'+entry.amount.toString(16).padStart(64,'0'),logIndex:'0x0'}]};
 throw Error('Unexpected RPC');
};
const service=new Persistence(db,auth,token,18,rpc,()=>now);
const passed:string[]=[];
const ok=(s:string)=>{passed.push(s);console.log('PASS',s);};
const sign=async(w:typeof a)=>{const c=await auth.challenge(w.address);return auth.verify(c.id,c.message,await w.signMessage(c.message));};
const record=(intent:any)=>{const hash='0x'+randomUUID().replaceAll('-','').padEnd(64,'0');burns.set(hash,{wallet:intent.wallet,amount:BigInt(intent.units),time:now});return hash;};
let server:ReturnType<typeof stagingServer>|undefined;
try{
 await db.query(readFileSync('server/migrations/001_staging.sql','utf8'));
 await db.query(readFileSync('server/migrations/002_auth_expiry.sql','utf8'));
 await db.query(readFileSync('server/migrations/003_submission_recovery.sql','utf8'));
 await db.query(readFileSync('server/migrations/004_shared_simulation.sql','utf8'));
 await db.query(readFileSync('server/migrations/005_trade_ledger.sql','utf8'));
 await db.query(readFileSync('server/migrations/012_burn_support.sql','utf8'));
 await db.query(readFileSync('server/migrations/009_reconciliation.sql','utf8'));
 await db.query(readFileSync('server/migrations/010_cancel_unsigned.sql','utf8'));
 await db.query(readFileSync('server/migrations/008_payment_mainnet.sql','utf8'));
 const challenge=await auth.challenge(a.address),signature=await a.signMessage(challenge.message);
 for(const changed of [challenge.message.replace(new URL(origin).host,'evil.invalid'),challenge.message.replace('Chain ID: '+chainId,'Chain ID: '+(chainId===4663?46630:4663)),challenge.message.replace(/Nonce: .*/,'Nonce: deadbeef')])await assert.rejects(auth.verify(challenge.id,changed,await a.signMessage(changed)));
 await assert.rejects(auth.verify(challenge.id,challenge.message,await b.signMessage(challenge.message)));
 const simultaneous=await Promise.allSettled(Array.from({length:12},()=>auth.verify(challenge.id,challenge.message,signature)));
 assert.equal(simultaneous.filter(r=>r.status==='fulfilled').length,1);ok('SIWE exact domain/network/nonce, wrong signer and 12-way single-use race');
 const sessionA=(simultaneous.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<string>).value,sessionB=await sign(b);
 await assert.rejects(new StagingAuth(db,origin,()=>now,chainId===4663?46630:4663).wallet(sessionA));
 await assert.rejects(new StagingAuth(db,'https://other.rattery.invalid',()=>now,chainId).wallet(sessionA));
 assert.equal((await service.overview(sessionA).catch(()=>null)),null);
 const late=await auth.challenge(a.address);now+=300001;await assert.rejects(auth.verify(late.id,late.message,await a.signMessage(late.message)));now-=300001;ok('Expired challenge rejected');
 const world=createWorld();await service.initialize(world);const ids=Object.keys(world.rats);
 if(chainId===4663){const unfunded=new Persistence(db,auth,token,18,async(m,p)=>m==='eth_call'?'0x0':rpc(m,p),()=>now);await assert.rejects(unfunded.reserve(sessionA,randomUUID(),ids[0],'mint','No funds'),/Insufficient/);assert.equal((await db.query('SELECT count(*) FROM care_intents')).rows[0].count,'0');ok('Unfunded mainnet wallet cannot reserve or block a rat');}
 const candidates=await Promise.allSettled(Array.from({length:24},(_,i)=>service.reserve(i%2?sessionA:sessionB,randomUUID(),ids[0],'mint','Stage Rat')));
 const wins=candidates.filter(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>[];assert.equal(wins.length,1);
 assert.equal(wins[0].value.chain_id,chainId);
 const winner=wins[0].value,owner=winner.wallet===a.address.toLowerCase()?sessionA:sessionB,foreign=owner===sessionA?sessionB:sessionA;
 assert.equal((await service.reserve(owner,winner.request_id,ids[0],'mint','Stage Rat')).id,winner.id);
 await assert.rejects(service.reserve(owner,winner.request_id,ids[1],'mint','Stage Rat'));
 await assert.rejects(service.finalize(foreign,winner.id,'0x'+'1'.repeat(64)));
 ok('24 concurrent mints yield one reservation; idempotency and foreign ownership protected');
 const attempts=await Promise.allSettled(Array.from({length:12},()=>service.beginSubmission(owner,winner.id)));
 assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);
 await assert.rejects(service.beginSubmission(foreign,winner.id));
 const hash=record(winner);
 await service.rememberSubmission(owner,winner.id,hash);
 assert.equal((await service.overview(owner)).intents.find(i=>i.id===winner.id)?.submitted_hash,hash);
 assert(!(await service.overview(foreign)).intents.some(i=>i.id===winner.id));
 ok('Single broadcast permission across 12 callers; wallet-scoped recovery hash');
 rpcDown=true;await assert.rejects(service.finalize(owner,winner.id,hash));rpcDown=false;
 assert.equal((await db.query('SELECT count(*) FROM burn_receipts')).rows[0].count,'0');
 await db.query("CREATE FUNCTION fail_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'simulated process failure'; END $$; CREATE TRIGGER fail_event BEFORE INSERT ON care_events FOR EACH ROW EXECUTE FUNCTION fail_event()");
 await assert.rejects(service.finalize(owner,winner.id,hash));
 assert.equal((await db.query('SELECT count(*) FROM burn_receipts')).rows[0].count,'0');
 await db.query('DROP TRIGGER fail_event ON care_events; DROP FUNCTION fail_event()');
 const recovered=new Persistence(db,new StagingAuth(db,origin,()=>now,chainId),token,18,rpc,()=>now);
 const final=await Promise.all(Array.from({length:16},()=>recovered.finalize(owner,winner.id,hash)));
 assert(final.every(x=>x.status==='applied'));
 assert.equal((await db.query('SELECT count(*) FROM care_events')).rows[0].count,'1');
 assert.equal((await db.query('SELECT count(*) FROM burn_receipts')).rows[0].count,'1');
 ok('RPC failure, transaction rollback, service recreation and 16 concurrent retries apply exactly once');
 await assert.rejects(service.reserve(foreign,randomUUID(),ids[0],'feed'));
 const duplicate=await service.reserve(owner,randomUUID(),ids[1],'mint','Second');
 await service.beginSubmission(owner,duplicate.id);
 // Unverified hints must not monopolize a receipt; only the verified ledger is unique.
 await service.rememberSubmission(owner,duplicate.id,hash);
 await assert.rejects(service.finalize(owner,duplicate.id,hash));
 assert.equal((await db.query('SELECT status FROM care_intents WHERE id=$1',[duplicate.id])).rows[0].status,'reserved');
 await assert.rejects(db.query('INSERT INTO rat_ownership(rat_id,wallet,mint_intent) VALUES($1,$2,$3)',[winner.rat_id,b.address.toLowerCase(),duplicate.id]));
 ok('Same on-chain receipt cannot purchase another rat; database ownership key rejects duplicate claim');
 // A valid confirmed burn remains recoverable after the app clock passes expiry:
 // RPC block timestamp is kept inside the original payment window for this case.
 const paid=record(duplicate),oldNow=now;
 const lateRpc=async(m:string,args:unknown[])=>m==='eth_getBlockByNumber'?{number:'0x64',hash:chainHash,timestamp:'0x'+Math.floor(oldNow/1000).toString(16)}:rpc(m,args);
 now+=600000;
 await assert.rejects(service.reserve(foreign,randomUUID(),ids[1],'mint','Contested'));
 const lateService=new Persistence(db,auth,token,18,lateRpc,()=>now);
 assert.equal((await lateService.finalize(owner,duplicate.id,paid)).status,'applied');ok('Confirmed in-window burn recovers after intent deadline without a second charge');

 // Eligibility can change while a payment confirms; retain evidence for resolution.
 const review=await service.reserve(sessionA,randomUUID(),ids[2],'mint','Review');
 const reviewHash=record(review);
 const state=(await db.query('SELECT * FROM colony_state WHERE id=1')).rows[0];
 state.world.rats[ids[2]].deadAt=0;
 await service.checkpoint(state.world,Number(state.revision));
 await assert.rejects(service.checkpoint(state.world,Number(state.revision)));
 assert.equal((await service.finalize(sessionA,review.id,reviewHash)).status,'review');
 assert.equal((await db.query('SELECT count(*) FROM burn_receipts WHERE intent_id=$1',[review.id])).rows[0].count,'1');
 assert.equal((await service.memorial('',1)).length,1);
 assert.equal((await service.memorial(ids[2],1)).length,0);
 await assert.rejects(service.memorial('',100000));
 ok('Paid ineligible action retained for review; stale checkpoint and unbounded memorial page rejected');
 const changed=(await db.query('SELECT * FROM colony_state WHERE id=1')).rows[0];
 changed.world.rats[ids[3]].motherId=ids[3];
 await assert.rejects(service.checkpoint(changed.world,Number(changed.revision)));
 assert.equal((await service.rat(ids[3])).motherId,null);
 ok('Genealogy cycle rejected atomically without corrupting identity');
 const careWorld=(await db.query('SELECT * FROM colony_state WHERE id=1')).rows[0];
 careWorld.world.rats[ids[0]].energy=.5;await service.checkpoint(careWorld.world,Number(careWorld.revision));
 const unsigned=await service.reserve(owner,randomUUID(),ids[0],'feed');
 await assert.rejects(service.cancel(foreign,unsigned.id));
 assert.equal((await service.cancel(owner,unsigned.id)).status,'cancelled');
 await assert.rejects(service.beginSubmission(owner,unsigned.id));
 const background=await service.reserve(owner,randomUUID(),ids[0],'feed');
 await service.beginSubmission(owner,background.id);await assert.rejects(service.cancel(owner,background.id));
 await service.rememberSubmission(owner,background.id,record(background));
 assert.equal((await service.reconcileSubmitted()).applied,1);
 assert.equal((await service.reconcileSubmitted()).checked,0);
 assert.equal((await db.query('SELECT status FROM care_intents WHERE id=$1',[background.id])).rows[0].status,'applied');
 ok('Unsigned cancellation is owner-only; submitted burn reconciles exactly once without browser/session');
 server=stagingServer(auth,service);await new Promise<void>(r=>server!.listen(0,'127.0.0.1',r));
 const port=(server.address() as {port:number}).port;
 const post=async(path:string,data:unknown,headers:Record<string,string>={})=>fetch('http://127.0.0.1:'+port+path,{method:'POST',headers:{origin,'content-type':'application/json',...headers},body:JSON.stringify(data)});
 assert.equal((await post('/auth/challenge',{address:a.address},{origin:'https://evil.invalid'})).status,403);
 assert.equal((await post('/care/reserve',{requestId:randomUUID(),ratId:ids[3],action:'mint',name:'X'})).status,401);
 assert.equal((await post('/auth/challenge',{padding:'x'.repeat(9000)})).status,413);
 const challengeResponse=await post('/auth/challenge',{address:a.address});
 const c=await challengeResponse.json() as any;
 const challengeCookies={cookie:challengeResponse.headers.get('set-cookie')!.split(';')[0]};
 assert.equal((await post('/auth/verify',{...c,signature:await a.signMessage(c.message)})).status,403);
 assert.equal((await post('/auth/verify',{...c,signature:await a.signMessage(c.message)},{cookie:'rattery_challenge='+c.id})).status,403);
 const response=await post('/auth/verify',{...c,signature:await a.signMessage(c.message)},challengeCookies);
 const cookie=response.headers.get('set-cookie')!;assert.equal(response.status,200);assert(cookie.includes('HttpOnly')&&cookie.includes('Secure')&&cookie.includes('SameSite=Strict'));
 const cookies={cookie:cookie.split(';')[0]};
 assert.equal((await (await post('/auth/session',{},cookies)).json() as any).wallet,a.address.toLowerCase());
 assert.equal((await post('/auth/verify',{...c,signature:await a.signMessage(c.message)},challengeCookies)).status,400);
 const reads=await Promise.all(Array.from({length:35},()=>post('/care/overview',{},cookies)));
 assert(reads.every(r=>r.status===200),'Observation must not consume the wallet mutation budget');
 const reserveResponse=await post('/care/reserve',{requestId:randomUUID(),ratId:ids[3],action:'mint',name:'HTTP Rat'},cookies);
 assert.equal(reserveResponse.status,200);
 const httpIntent=await reserveResponse.json() as any;
 assert.equal((await post('/care/finalize',{id:httpIntent.id,hash:record(httpIntent)},cookies)).status,200);
 const walletBurst=await Promise.all(Array.from({length:35},()=>post('/care/finalize',{id:httpIntent.id,hash:record(httpIntent)},cookies)));
 assert(walletBurst.some(r=>r.status===429));ok('Per-wallet burst limit');
 await post('/auth/logout',{},cookies);
 assert.equal((await post('/care/reserve',{requestId:randomUUID(),ratId:ids[3],action:'feed'},cookies)).status,401);
 ok('HTTP signed login → reservation → verified burn → mint → logout; CSRF, body size and secure cookies');
 const requests=await Promise.all(Array.from({length:110},()=>post('/unknown',{})));
 assert(requests.some(r=>r.status===429));ok('Persistent rate limit rejects request burst');
 await auth.logout(sessionA);await assert.rejects(auth.wallet(sessionA));
 now+=3600001;await assert.rejects(auth.wallet(sessionB));ok('Logout and session expiration');
 mkdirSync('test-results/persistence',{recursive:true});
 writeFileSync('test-results/persistence/report.json',JSON.stringify({passed,scope:'Real PostgreSQL; real ephemeral EOA signatures; controlled RPC receipts. No blockchain transaction broadcast.',schema},null,2));
 console.log('ALL PASS',passed.length);
}finally{
 if(server)await new Promise<void>(r=>server!.close(()=>r()));
 await db.end();
 // Keep this isolated schema for backup/restore verification; no production DB touched.
}
