import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {inspectPool,TOPIC,decodeSwap,resolveLaunch} from '../api/_lib/pons';
import {wordSigned,toFloat} from '../api/_lib/eth';
const read=(name:string)=>JSON.parse(readFileSync('test-results/'+name,'utf8').replace(/^\uFEFF/,''));
const c=read('mainnet-biscotti-capture.json'),secondary=read('biscotti-secondary-pool-initialize.json').result[0],metadata=read('secondary-quote-token.json');
const native=inspectPool(c.logs.find((l:any)=>l.topics[0]===TOPIC.initializeV4),c.token);
const extra=inspectPool(secondary,c.token);
assert(native.nativeQuote);assert(!extra.nativeQuote);assert.equal(extra.quoteToken,metadata.address_hash.toLowerCase());assert.equal(Number(metadata.decimals),6);assert.equal(metadata.symbol,'USDG');
assert.throws(()=>inspectPool(secondary,'0x1111111111111111111111111111111111111111'),/does not contain/);
assert.throws(()=>inspectPool({...secondary,topics:[secondary.topics[0],'0x'+'0'.repeat(64),...secondary.topics.slice(2)]},c.token),/does not match/);
assert.throws(()=>inspectPool({...secondary,data:'0x'},c.token),/Malformed/);
const receipt=read('mainnet-biscotti-recent-receipt.json');const swaps=receipt.logs.filter((l:any)=>l.topics[0]===TOPIC.swapV4&&l.topics[1]===extra.poolId);
assert(swaps.length>0);
const amounts=swaps.map((l:any)=>{const signedQuote=wordSigned(l.data,extra.tokenIs1?0:1),quote=Math.abs(toFloat(signedQuote,Number(metadata.decimals))),wrongEth=decodeSwap(l,extra.tokenIs1)!.eth;assert(Math.abs(quote/wrongEth-1e12)<1);return {tx:l.transactionHash,quoteAmount:quote,quoteSymbol:metadata.symbol,incorrectEthAmount:wrongEth};});
process.env.RATTERY_CHAIN_ID='4663';process.env.RATTERY_CA=c.token;process.env.RATTERY_BIRTH_BLOCK=String(c.birthBlock);process.env.RATTERY_RPC='http://unsupported-quote-test';
const event=structuredClone(c.receipt.logs.find((l:any)=>l.topics[0]===TOPIC.tokenLaunched));event.data='0x'+extra.quoteToken.slice(2).padStart(64,'0')+event.data.slice(66);
const original=globalThis.fetch;globalThis.fetch=(async(_url:any,init:any)=>{const q=JSON.parse(init.body);return Response.json({jsonrpc:'2.0',id:q.id,result:q.method==='eth_chainId'?'0x1237':[event]});}) as typeof fetch;
await assert.rejects(resolveLaunch,/Unsupported quote token/);
event.data=c.receipt.logs.find((l:any)=>l.topics[0]===TOPIC.tokenLaunched).data;
process.env.RATTERY_POOL_ID=extra.poolId;
await assert.rejects(resolveLaunch,/verified currency metadata/);
delete process.env.RATTERY_POOL_ID;globalThis.fetch=original;
writeFileSync('test-results/pool-coverage-test.json',JSON.stringify({native,secondary:extra,quoteDecimals:Number(metadata.decimals),amounts,unrelatedPoolRejected:true,tamperedKeyRejected:true,unsupportedLaunchQuoteRejected:true,unverifiedOverrideRejected:true,scope:'Verification/classification only. Secondary pools are not yet aggregated into the ETH feed.'},null,2));
console.log('PASS: native pool, USDG pool, 6-decimal quote, 1e12 scaling mismatch prevented at launch resolution, unrelated and tampered pools');
