import assert from 'node:assert/strict';
import * as T from 'three';
import {RatAssets,RatModel} from '../src/render/RatModel';
import {createWorld} from '../src/sim/colony';
const assets=new RatAssets(),rat=Object.values(createWorld().rats)[0],model=new RatModel(assets,rat.id,true),camera=new T.PerspectiveCamera();
const visibleMeshes=()=>{let count=0;model.root.traverseVisible(o=>{if(o instanceof T.Mesh)count++;});return count;};
camera.position.set(0,5,5);model.sync(rat,1,1/60,0,false,false,camera);const baseline=visibleMeshes();
for(const distance of [17.99,18,18.01,29.99,30,30.01,60,95,150]){camera.position.set(0,0,distance);model.sync(rat,1,1/60,0,false,false,camera);assert.equal(visibleMeshes(),baseline,`Anatomy changed at distance ${distance}`);}
// Movement generated by social paths can arrive with zero simulation velocity.
rat.vx=rat.vy=0;rat.y+=5;
let lastHeading=model.root.rotation.y;
for(let i=0;i<120;i++){model.sync(rat,1,1/60,i/60,false,false,camera);const turn=Math.atan2(Math.sin(model.root.rotation.y-lastHeading),Math.cos(model.root.rotation.y-lastHeading));assert(Math.abs(turn)<=2.4/60+1e-6,"Turn exceeded anatomical limit");lastHeading=model.root.rotation.y;}
assert(Math.abs(model.root.rotation.y+Math.PI/2)<.1,'Heading should follow visible displacement');
model.sync(rat,1,1/60,1,true,true,camera);
model.root.traverse(o=>{for(const n of [...o.position.toArray(),...o.scale.toArray(),...o.quaternion.toArray()])assert(Number.isFinite(n));});
model.dispose();assets.dispose();console.log('PASS: anatomy at nine zoom distances, social movement heading, reduced motion and finite transforms');
