import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {Wallet} from 'ethers';
import {Persistence,ENGINE_VERSION,MAX_SIMULATION_BATCH} from '../server/persistence.js';
import {StagingAuth} from '../server/auth.js';
import {startSimulationWorker} from '../server/simulation-worker.js';
import {createWorld,kill} from '../src/sim/colony.js';
import {ecologyStep} from '../src/sim/ecology.js';
import {burnCall} from '../src/market/burn.js';
import {CONFIG} from '../src/config.js';
if(!process.env.PGDATABASE?.endsWith('_test'))throw Error('Isolated test database required');
const schema='engine_'+randomUUID().replaceAll('-',''),admin=new Pool();
await admin.query('CREATE SCHEMA '+schema);await admin.end();
const db=new Pool({max:20,options:'-c search_path='+schema+',public'});
let now=1800000000123;const wallet=Wallet.createRandom(),token='0x'+'a'.repeat(40);
const burns=new Map<string,{amount:bigint,time:number}>(),blockHash='0x'+'b'.repeat(64);
let latestTime=now;
const rpc=async(method:string,args:unknown[])=>{
 if(method==='eth_chainId')return '0xb626';if(method==='eth_blockNumber')return '0x64';
 if(method==='eth_getBlockByNumber')return {number:'0x60',hash:blockHash,timestamp:'0x'+Math.floor(latestTime/1000).toString(16)};
 const hash=String(args[0]),b=burns.get(hash);if(!b)return null;
 if(method==='eth_getTransactionByHash'){latestTime=b.time;return {hash,from:wallet.address,to:token,input:burnCall(token,b.amount).data,value:'0x0'};}
 if(method==='eth_getTransactionReceipt')return {transactionHash:hash,from:wallet.address,to:token,status:'0x1',blockNumber:'0x60',blockHash,logs:[{address:token,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+wallet.address.slice(2).toLowerCase().padStart(64,'0'),'0x'+'0'.repeat(64)],data:'0x'+b.amount.toString(16).padStart(64,'0'),logIndex:'0x0'}]};
 throw Error('Unexpected RPC');
};
const passed:string[]=[];const ok=(s:string)=>{passed.push(s);console.log('PASS',s);};
try{
 for(const f of ['001_staging','002_auth_expiry','003_submission_recovery','004_shared_simulation'])await db.query(readFileSync('server/migrations/'+f+'.sql','utf8'));
 const auth=new StagingAuth(db,'http://localhost:18756',()=>now),service=new Persistence(db,auth,token,18,rpc,()=>now);
 const c=await auth.challenge(wallet.address),session=await auth.verify(c.id,c.message,await wallet.signMessage(c.message));
 const world=createWorld();world.realStartedAt=now;ecologyStep(world,0);const ratId=Object.keys(world.rats)[0];world.rats[ratId].energy=.4;
 await service.initialize(world);assert.equal((await service.advanceSimulation()).steps,0);
 const mint=await service.reserve(session,randomUUID(),ratId,'mint','Shared Rat');
 const hash='0x'+'1'.repeat(64);burns.set(hash,{amount:BigInt(mint.units),time:now});
 now+=1000;
 const racing=await Promise.all([service.finalize(session,mint.id,hash),...Array.from({length:12},()=>service.advanceSimulation())]);
 assert.equal((await service.sharedSnapshot()).tick,10);
 let snapshot=await service.sharedSnapshot();assert.equal(snapshot.world.care?.owners[ratId],wallet.address.toLowerCase());assert.equal(snapshot.world.rats[ratId].name,'Shared Rat');
 assert.equal(racing.filter(x=>'steps' in x&&x.steps>0).length,1);
 ok('12 workers and mint serialize: ten ticks total, one owner, no lost mint');
 const stale=snapshot;
 const feed=await service.reserve(session,randomUUID(),ratId,'feed');const feedHash='0x'+'2'.repeat(64);burns.set(feedHash,{amount:BigInt(feed.units),time:now});
 const beforeEnergy=snapshot.world.rats[ratId].energy;now+=100;
 await Promise.all([service.finalize(session,feed.id,feedHash),service.advanceSimulation()]);
 snapshot=await service.sharedSnapshot();assert(snapshot.world.rats[ratId].energy>beforeEnergy+.14);assert.equal(snapshot.world.care?.lastSequence,2);
 await assert.rejects(service.checkpoint(stale.world,stale.revision),/Stale/);
 ok('Concurrent feeding survives subsequent biology; stale snapshot cannot overwrite it');
 const baseline=await service.sharedSnapshot(),start=now;
 now+=2000;await service.advanceSimulation();const batched=await service.sharedSnapshot();
 await db.query('UPDATE colony_state SET world=$1,simulation_tick=$2,simulation_at=$3',[baseline.world,baseline.tick,baseline.at]);
 for(let i=1;i<=20;i++)await new Persistence(db,auth,token,18,rpc,()=>now).advanceSimulation(start+i*100);
 const restarted=await service.sharedSnapshot();assert.deepEqual(restarted.world,batched.world);assert.equal(restarted.tick,batched.tick);
 ok('Twenty reconstructed workers match one batch byte-for-byte in world and RNG state');
 const beforeFailure=await service.sharedSnapshot();
 await db.query("CREATE FUNCTION fail_tick() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'simulated worker failure'; END $$; CREATE TRIGGER fail_tick BEFORE UPDATE ON colony_state FOR EACH ROW EXECUTE FUNCTION fail_tick()");
 now+=100;await assert.rejects(service.advanceSimulation());assert.deepEqual(await service.sharedSnapshot(),beforeFailure);
 await db.query('DROP TRIGGER fail_tick ON colony_state; DROP FUNCTION fail_tick()');
 assert.equal((await service.advanceSimulation()).steps,1);
 ok('Worker transaction failure rolls back world, RNG and cursor; retry advances once');
 now+=10000;await assert.rejects(service.reserve(session,randomUUID(),ratId,'water'),/catching up/);
 const catchup=await service.advanceSimulation();assert.equal(catchup.steps,MAX_SIMULATION_BATCH);assert.equal(catchup.lagMs,6000);
 await service.advanceSimulation();await service.advanceSimulation();assert.equal((await service.advanceSimulation()).steps,0);
 const at=await service.sharedSnapshot();assert.equal((await service.advanceSimulation(now-1000)).steps,0);assert.deepEqual(await service.sharedSnapshot(),at);
 ok('Catch-up is bounded and retains backlog; payments wait; clock rollback does not rewind');
 const [readerA,readerB]=await Promise.all([service.sharedSnapshot(),new Persistence(db,auth,token,18,rpc,()=>now).sharedSnapshot()]);assert.deepEqual(readerA,readerB);
 assert.equal(readerA.world.care?.lastSequence,2);assert.equal(readerA.world.care?.owners[ratId],wallet.address.toLowerCase());
 ok('Independent readers receive identical persisted colony and care');
 await db.query("UPDATE colony_state SET engine_version='incompatible'");await assert.rejects(service.advanceSimulation(),/version mismatch/);
 await db.query('UPDATE colony_state SET engine_version=$1',[ENGINE_VERSION]);
 ok('Incompatible engine version fails closed');
 const death=await service.sharedSnapshot();kill(death.world,death.world.rats[ratId],'age');await service.checkpoint(death.world,death.revision);now+=100;await service.advanceSimulation();
 assert((await service.rat(ratId)).deadAt!==null);assert((await service.memorial()).some(r=>r.id===ratId));assert.equal((await service.sharedSnapshot()).world.care?.owners[ratId],wallet.address.toLowerCase());
 ok('Death and memorial retain paid identity and ownership across ticks');
 const cursor=(await service.sharedSnapshot()).tick,errors:unknown[]=[];now+=500;
 const stop=startSimulationWorker(service,e=>errors.push(e),50);
 for(let i=0;i<100;i++){if((await service.sharedSnapshot()).tick>=cursor+5)break;await new Promise(r=>setTimeout(r,10));}
 await stop();assert.deepEqual(errors,[]);assert.equal((await service.sharedSnapshot()).tick,cursor+5);
 ok('Background worker advances without observers and stops cleanly');
 mkdirSync('test-results/shared-simulation',{recursive:true});writeFileSync('test-results/shared-simulation/report.json',JSON.stringify({passed,schema,engineVersion:ENGINE_VERSION,tickMs:CONFIG.time.tickMs,scope:'Real isolated PostgreSQL, controlled payment receipts, actual biology engine'},null,2));
 console.log('ALL PASS',passed.length);
}finally{await db.end();}
