import assert from 'node:assert/strict';
import {fetchAllHistory} from '../src/market/onchain';
import {createWorld} from '../src/sim/colony';
import {worldRng} from '../src/sim/rng';
import {makeReplay} from '../src/sim/replay';
import {decodeCurve,decodeSwap,TOPIC,resolveLaunch} from '../api/_lib/pons';
const nativeFetch=globalThis.fetch;
const base='http://127.0.0.1:8788';
const chain=await (await nativeFetch(base+'/api/chain')).json();assert.equal(chain.chainId,46630);assert.equal(chain.ok,true);assert.equal(chain.launch.phase,'curve');assert.equal(chain.launch.progress,.5);
for(const chunk of ['-1','1e100','bad'])assert.equal((await nativeFetch(base+'/api/trades?chunk='+chunk)).status,400);
const res=await nativeFetch(base+'/api/trades?chunk=0');assert(res.headers.get('cache-control')?.includes('immutable'));const body=await res.json();assert.equal(body.trades.length,4);assert.deepEqual(body.trades.map((t:any)=>t.side),['buy','sell','sell','buy']);assert.equal(body.trades[3].trader,'0x6666666666666666666666666666666666666666');
globalThis.fetch=((url:any,init:any)=>nativeFetch(typeof url==='string'&&url.startsWith('/api/')?base+url:url,init)) as typeof fetch;
const history=await fetchAllHistory(2);assert.equal(history.trades.length,5);assert.equal(history.trades[4].usd,2400);
const w=createWorld(9),clone=JSON.parse(JSON.stringify(w));const opts={t0:history.t0,targetTick:400,tickMs:100,dtDays:1/600,maxTicks:400};const a=makeReplay(w,worldRng(w),history.trades,opts),b=makeReplay(clone,worldRng(clone),history.trades,opts);a.step(400);while(!b.done())b.step(13);assert.deepEqual(w,clone);
globalThis.fetch=((url:any,init:any)=>String(url).includes('chunk=1')?Promise.resolve(new Response('',{status:503})):nativeFetch(base+url,init)) as typeof fetch;
await assert.rejects(()=>fetchAllHistory(2),/503/);
assert.throws(()=>decodeCurve({topics:[TOPIC.curveBuy],data:'0x'} as any),/Malformed/);assert.throws(()=>decodeSwap({topics:[],data:'0x'} as any,true),/Malformed/);
process.env.RATTERY_CHAIN_ID='46630';process.env.RATTERY_CA='0x1111111111111111111111111111111111111111';process.env.RATTERY_BIRTH_BLOCK='1';globalThis.fetch=(async()=>new Response(JSON.stringify({result:'0x1237'}),{headers:{'content-type':'application/json'}})) as typeof fetch;
await assert.rejects(resolveLaunch,/chain mismatch/);globalThis.fetch=nativeFetch;
console.log('PASS: synthetic testnet API → decode → HTTP chunks → frontend adapter → replay, signs, wallet, USD conversion, invalid chunks, missing history, malformed logs and wrong network');
