import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {Persistence} from '../server/persistence.js';
import {TradeLedger,type MarketBlock,type MarketEvent} from '../server/trade-ledger.js';
import {StagingAuth} from '../server/auth.js';
import {createWorld} from '../src/sim/colony.js';
if(!process.env.PGDATABASE?.endsWith('_test'))throw Error('Isolated test database required');
const schema='ledger_'+randomUUID().replaceAll('-',''),admin=new Pool();
await admin.query('CREATE SCHEMA '+schema);await admin.end();
const db=new Pool({max:20,options:'-c search_path='+schema+',public'});
let now=1800000000000;
const token='0x'+'a'.repeat(40),h=(n:number)=>'0x'+n.toString(16).padStart(64,'0');
const auth=new StagingAuth(db,'http://localhost:18756',()=>now);
const service=new Persistence(db,auth,token,18,async()=>{throw Error('No RPC writes or wallet needed');},()=>now);
const ledger=new TradeLedger(service,new Set(['fixture']));
const quote={source:'fixture',observedAt:now,usdMicrosPerEth:'2000000000'};
const event=(n:number,logIndex=0,ethWei='10000000000000000'):MarketEvent=>({chainId:4663,token,hash:h(n+1000),logIndex,timestamp:1800000000000,ethWei,side:'buy',venue:'curve',trader:token});
const block=(n:number,events:MarketEvent[]=[]):MarketBlock=>({number:n,hash:h(n),parentHash:h(n-1),timestamp:1800000000000,events});
const count=async()=>Number((await db.query("SELECT count(*) FROM colony_trades WHERE status='applied'")).rows[0].count);
let groups=0;const ok=(s:string)=>console.log('PASS',++groups,s);
try{
 for(const f of ['001_staging','002_auth_expiry','003_submission_recovery','004_shared_simulation','005_trade_ledger','012_burn_support'])await db.query(readFileSync('server/migrations/'+f+'.sql','utf8'));
 const world=createWorld();world.realStartedAt=now;await service.initialize(world);await service.advanceSimulation();
 await ledger.initialize(4663,token,{number:10,hash:h(10),timestamp:now});
 const concurrent=await Promise.all(Array.from({length:12},()=>ledger.ingest(block(11,[event(11)]),quote)));
 assert.equal(concurrent.filter(r=>!r.duplicate).length,1);
 const before=await service.sharedSnapshot();now+=100;await Promise.all(Array.from({length:8},()=>service.advanceSimulation()));
 assert.equal(await count(),1);assert.equal((await service.sharedSnapshot()).tick,1);
 assert((await service.sharedSnapshot()).world.env.food>before.world.env.food);
 await service.advanceSimulation();assert.equal(await count(),1);
 ok('12 competing ingestors and eight workers apply one trade once');
 await ledger.ingest(block(12),null);
 await assert.rejects(ledger.ingest(block(14),quote),/Noncontiguous/);
 await assert.rejects(ledger.ingest(block(13,[{...event(13),token:'0x'+'b'.repeat(40)}]),quote),/identity/);
 await assert.rejects(ledger.ingest(block(13,[event(13),event(13)]),quote),/Duplicate/);
 assert.equal(Number((await db.query('SELECT last_block FROM trade_stream')).rows[0].last_block),12);
 ok('Empty blocks advance the cursor; gaps, foreign tokens and duplicate logs reject atomically');
 const waiting=event(13);await ledger.ingest(block(13,[waiting]),null);
 await ledger.ingest(block(14,[event(14)]),quote);now+=100;await service.advanceSimulation();assert.equal(await count(),1);
 const id=4663+':'+token+':'+waiting.hash+':0';
 await assert.rejects(ledger.resolve(id,{...quote,source:'untrusted'}),/Invalid historical quote/);
 await assert.rejects(ledger.resolve(id,{...quote,observedAt:quote.observedAt-300001}),/Invalid historical quote/);
 await ledger.resolve(id,quote);await ledger.resolve(id,quote);
 await assert.rejects(ledger.resolve(id,{...quote,usdMicrosPerEth:'3000000000'}),/immutable/);
 now+=100;await service.advanceSimulation();assert.equal(await count(),3);
 const applied=(await db.query('SELECT applied_tick,applied_at FROM colony_trades WHERE block_number IN (13,14)')).rows;
 assert(applied.every(r=>Number(r.applied_tick)===3&&Number(r.applied_at)===now));
 ok('Missing quote queues ordered effects, rejects stale prices and preserves immutable valuation');
 await ledger.ingest(block(15,[event(15)]),quote);
 const baseline=await service.sharedSnapshot();
 await db.query("CREATE FUNCTION fail_tick() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected rollback'; END $$; CREATE TRIGGER fail_tick BEFORE UPDATE ON colony_state FOR EACH ROW EXECUTE FUNCTION fail_tick()");
 now+=100;await assert.rejects(service.advanceSimulation(),/injected/);assert.equal(await count(),3);assert.deepEqual(await service.sharedSnapshot(),baseline);
 await db.query('DROP TRIGGER fail_tick ON colony_state; DROP FUNCTION fail_tick()');
 const fresh=new Persistence(db,auth,token,18,async()=>null,()=>now);await fresh.advanceSimulation();assert.equal(await count(),4);
 ok('Failure after effects rolls back ledger and world together; reconstructed worker retries once');
 const thresholds=['24995000000000000','25000000000000000','125000000000000000','250000000000000000','500000000000000000'];
 await ledger.ingest(block(16,thresholds.map((wei,i)=>event(16,i,wei)).reverse()),quote);
 const tiers=(await db.query("SELECT valuation->>'tier' AS tier FROM colony_trades WHERE block_number=16 ORDER BY log_index")).rows.map(r=>r.tier);
 assert.deepEqual(tiers,['light','small','medium','large','giant']);
 now+=100;await fresh.advanceSimulation();assert.equal(await count(),9);
 ok('Exact USD boundaries match approved tiers and unordered logs normalize canonically');
 await ledger.ingest(block(17,Array.from({length:205},(_,i)=>event(17,i))),quote);
 now+=100;await fresh.advanceSimulation();assert.equal(await count(),209);
 now+=100;await fresh.advanceSimulation();assert.equal(await count(),214);
 ok('A burst is bounded to 200 events per tick and retains all remaining events');
 await assert.rejects(ledger.ingest({...block(18),timestamp:now+1000},quote),/Future/);
 await assert.rejects(ledger.ingest(block(18,[event(18,0,'9'.repeat(78))]),quote),/range/);
 assert.equal(Number((await db.query('SELECT last_block FROM trade_stream')).rows[0].last_block),17);
 const sell={...event(18,0,'500000000000000000'),side:'sell' as const};
 const snapshotBeforeSell=await service.sharedSnapshot();
 // Allow the reaction cooldown to expire, without changing the approved budget.
 now+=11000;while((await service.advanceSimulation()).lagMs>=100){}
 await ledger.ingest(block(18,[sell]),quote);
 now+=100;await service.advanceSimulation();
 assert.equal(await count(),215);
 assert((await service.sharedSnapshot()).world.env.sellPressure>snapshotBeforeSell.world.env.sellPressure);
 ok('Future blocks and excessive amounts reject; a giant sell changes shared sell pressure');
 await ledger.ingest(block(19,[event(19)]),quote);
 await assert.rejects(ledger.ingest({...block(19,[event(19)]),hash:h(999)},quote),/halted/);
 now+=100;await fresh.advanceSimulation();assert.equal(await count(),215);
 assert.equal((await db.query('SELECT halted FROM trade_stream')).rows[0].halted,true);
 await assert.rejects(ledger.ingest(block(20),quote),/unavailable/);
 ok('Changed historical block persists a halt and prevents further market effects');
 // Isolated fault scenario: operator unlock only to test a different conflict.
 await db.query('UPDATE trade_stream SET halted=false');
 await assert.rejects(ledger.ingest({...block(20),parentHash:h(123)},quote),/halted/);
 assert.equal((await db.query('SELECT halted FROM trade_stream')).rows[0].halted,true);
 assert.equal(Number((await db.query('SELECT last_block FROM trade_stream')).rows[0].last_block),19);
 ok('Parent mismatch halts without silently replacing the accepted cursor');
 await db.query('UPDATE trade_stream SET halted=false');
 const range=[20,21,22].map(n=>({block:block(n,[event(n)]),quote}));
 await db.query("CREATE FUNCTION fail_batch() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.block_number=21 THEN RAISE EXCEPTION 'batch rollback'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_batch BEFORE INSERT ON colony_trades FOR EACH ROW EXECUTE FUNCTION fail_batch()");
 await assert.rejects(ledger.ingestRange(range),/batch rollback/);
 assert.equal(Number((await db.query('SELECT last_block FROM trade_stream')).rows[0].last_block),19);
 assert.equal(Number((await db.query('SELECT count(*) FROM trade_blocks WHERE block_number>=20')).rows[0].count),0);
 await db.query('DROP TRIGGER fail_batch ON colony_trades; DROP FUNCTION fail_batch()');
 await ledger.ingest(range[0].block,quote);
 await ledger.ingestRange(range);
 assert.equal((await ledger.ingestRange(range)).duplicate,true);
 assert.equal(Number((await db.query('SELECT count(*) FROM colony_trades WHERE block_number>=20')).rows[0].count),3);
 ok('Range commit is atomic and overlapping retries insert only the missing suffix');
 console.log('ALL PASS',groups);
}finally{await db.end();}
